language: java
sudo: false # faster builds

jdk:
  - openjdk8

cache: bundler

script:
 - mvn --version
 - mvn clean package
 - mvn test
 - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)