version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: >-
    mvn clean install

    mvn cobertura:cobertura
test_script:
- cmd: >-
    mvn --version

    mvn test
    
after_success:
  - bash <(curl -s https://codecov.io/bash)