# Test against the latest version of this java version
environment:
  stack: jdk 1.8

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of maven
  - ps: mvn package

# To build.
build: mvn clean install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - mvn --version
  # run tests
  - mvn test

