version: 1.0.{build}
image: Visual Studio 2015
build_script:
- cmd: >-
    mvn clean install

    mvn cobertura:cobertura
test_script:
- cmd: >-
    mvn --version

    mvn test

    pip install codecov
    
    dir
     
    cd target/surefire-reports
    
    ls
    
    codecov -f TEST-SeptiemeSemaine.FirstTD.firstClassTest.xml
    
    bash <(curl -s https://codecov.io/bash)